# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da9f879dfc46f30abdf097629f8bfb97ffb8eaa82ef39e163b5a735cd6012375ae979920924e577a9f238545723f74d0b8731dde83390bc3e086431314b9cdc

test:
  secret_key_base: b0f0c0546ce77c7a785cde0773d669462021136fafe9dbb94f27f0a5f48788c4590434e3d7cf07e9fa63f84400b0a3645254194728e03bfb8aef545b32bf0234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
